### ISSUE TITLE
IPD gets stuck when activating a gait that is not possible (in the state machine).

### ISSUE THREAD

**Issue by KarlijndeJong** [project-march/input-device#34]
when performing a gait that is not possible the input device does not get feedback from the exoskeleton that this is not possible. It will stay in its activating screen and then it is not possible to go back or do anything.

**Comment by martijnvandermarel** [comment]
Option: make a branch that doesn't require the exoskeleton feedback and use that branch for testing code quickly.

**Comment by Olavhaasie** [comment]
A demo environment has been implemented in #47
