### ISSUE TITLE
Input device home stand doesn't work with exoskeleton

### ISSUE THREAD

**Issue by JimKieft** [project-march/input-device#39]

**Comment by martijnvandermarel** [comment]
More info: real issue noticed while training was that ipd gets stuck when homing to stand is activated. This is most likely a software bug in the ipd software

**Comment by martijnvandermarel** [comment]
i checked, and develop doesn't have HomeStandStartActivated in the stateToGaitMapping. So should be an easy fix. Don't forget to upload to real IPD when fixed
